version: "3"
services:
  server:
    build:
      context: ../dzencode_inventory-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # Дополнительные параметры для сервера

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # Дополнительные параметры для клиента
